import { Inter } from 'next/font/google'
import './globals.css'
import Header from './componets/Header'
import Providers from "../reduxStore/storeProvider"


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header/>
          <div className='cont'>{children}</div>
          <script type = "module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
        </Providers>
      </body>
    </html>
  )
}
